name: 'Skip Duplicate Actions'
description: 'Skip duplicate workflow-runs. Skip or ignore specific paths. Cancel outdated workflow-runs.'
author: fkirc
branding:
  icon: 'stop-circle'
  color: 'white'
inputs:
  github_token:
    description: 'Your GitHub Access Token'
    required: true
  paths_ignore:
    description: 'A JSON-array with ignored path patterns, e.g. something like ["**/README.md", "**/docs/**"]'
    required: false
    default: '[]'
  paths:
    description: 'A JSON-array with path patterns, e.g. something like ["platform-specific/**"]'
    required: false
    default: '[]'
  cancel_others:
    description: 'If true, then workflow-runs from outdated commits will be cancelled'
    required: false
    default: 'true'
  do_not_skip:
    description: 'A JSON-array with triggers that should never be skipped'
    required: false
    default: '["workflow_dispatch", "schedule"]'
  concurrent_skipping:
    description: 'If false, unfinished workflow-runs will be safely ignored'
    required: false
    default: 'true'

outputs:
  should_skip:
    description: 'true if the current run can be safely skipped. This should be evaluated for either individual steps or entire jobs.'
runs:
  using: 'node12'
  main: 'dist/index.js'
