on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '0 12 18 * *'

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ github.token }}

  build:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - run: npm run build
      - run: git diff --exit-code # Ensure that JS in dist was re-compiled
