on: [push, workflow_dispatch]

jobs:
  self_test:
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-action-runs@master
        id: skip
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "Did not skip execution for output ${{ steps.skip.outputsss.is_duplicate }}"
        if: ${{ ! steps.skip.outputs.is_duplicate }}
