on: [push, workflow_dispatch, pull_request]

jobs:
  pre_job:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ github.token }}
          paths_ignore: '["**/README.md", "**/docs/**"]'

  main_job:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running slow tests..." && sleep 30



  skip_individual_steps_job:
    runs-on: ubuntu-latest
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ github.token }}
          paths: '["src/**", "dist/**"]'
      - if: ${{ steps.skip_check.outputs.should_skip == 'false' }}
        run: |
          echo "Run only if src/ or dist/ changed..." && sleep 30
          echo "Do other stuff..."



  private_action:
    runs-on: ubuntu-latest
    steps:
      # To use the Action from the current branch, we checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
      - id: skip_check
        uses: ./ # Uses this Action in the root directory
        with:
          github_token: ${{ github.token }}
          paths_ignore: '["**/*.yml"]'
          cancel_others: 'false'
      - if: ${{ steps.skip_check.outputs.should_skip == 'false' }}
        run: |
          echo "Do stuff..." && sleep 30
