on: [push, workflow_dispatch, pull_request]

jobs:
  pre_job:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ github.token }}
          cancel_self: 'false'

  simple_usage:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running slow tests..." && sleep 30

  advanced_usage:
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        id: skip
        with:
          github_token: ${{ github.token }}
          cancel_self: 'false'
      - if: ${{ steps.skip.outputs.should_skip == 'false' }}
        run: |
          echo "Running slow tests..." && sleep 30
          echo "Do other stuff..."

  private_action:
    runs-on: ubuntu-latest
    steps:
      # To use the Action from the current branch, we checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: skip-duplicate-actions
        uses: ./ # Uses this Action in the root directory
        with:
          github_token: ${{ github.token }}
          cancel_others: 'false'
      - run: echo "Running slow tests..." && sleep 30
